### ISSUE TITLE
How about decoding the label? 

### ISSUE THREAD

**Issue by stoneyang** [audioset/ontology#10]
Hi, there: 

Just wondering how to decode the labels: 

```
/m/06mb1,/m/0jb2l,/m/0ngt1,/t/dd00038
```

Thanks.

**Comment by dpwe** [comment]
You look them up in
https://github.com/audioset/ontology/blob/master/ontology.json

/m/06mb1: Rain

/m/0jb2l: Thunderstorm

/m/0ngt1: Thunder

/t/dd00038: Rain on surface

**Comment by stoneyang** [comment]
> /m/06mb1

Thanks very much!
