### ISSUE TITLE
Quality Assessment and rerating File Not Downloadable

### ISSUE THREAD

**Issue by lijuncheng16** [audioset/ontology#7]
Hi, there:
The Quality Assessment and rerating file at: 
https://research.google.com/audioset/download.html 
is not downloadable.
Namely, qa_true_counts.csv rerated_video_ids.txt are both not available. Could you fix this?

Thank you!

**Comment by dpwe** [comment]
They are both working for me. Can you try again?

Also, what country are you accessing from?  It’s possible Google Cloud
automatically switches server by region.

Thanks,

  DAn.

**Comment by lijuncheng16** [comment]
Thank you for the prompt response! I got them now through accessing the embedded links directly. Happy thanksgiving!
